### ISSUE TITLE
No way to ablate on individual features specified in feature files

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#315] opened 2016-03-02 23:04 UTC
In some cases, one has a few different feature files with each file containing a set of features (i.e., numeorus columns). It's a simple matter to do ablation between the feature files or even groups of feature files, but it seems to be impossible to do ablation with every single feature. For example, say I have a file `a.tsv` in which features `a1` and `a2` are provided and then I have another file `b.tsv` in which features `b1` and `b2` are provided. If I want to do ablation with `a1`, `a1`+`a2`, `a2`, `b1`, `b1`+`b2`, `b2`, `a1`+`a2`+`b1`, etc., i.e., every combination of the indivdual features, this will be impossible with the current setup unless I split up `a.tsv` and `b.tsv` into, say, `a1.tsv`, `a2.tsv`, `b1.tsv`, etc., and then specify each as a different feature set. It would be nice if there were some way to use the individual features in a file.

**Comment by dan-blanchard** [comment] 2016-03-03 14:58
Looks like you accidentally created the same issue twice.  Closing as duplicate of #314.

**Closed by dan-blanchard** 2016-03-03 14:58 UTC
Labels: documentation, enhancement

**Comment by mulhod** [comment] 2016-03-04 05:14
Whoops. I think I was just trying to edit something.
