### ISSUE TITLE
get warning with learning curves unnecessarily

### ISSUE THREAD

**Issue by aoifecahill** [EducationalTestingService/skll#410] opened 2018-01-28 18:30 UTC
I get the following warning even though I do not have `objectives` specified in my config file. We should probably only output the warning when `objectives` is specified, otherwise it is confusing. 

`WARNING : Ignoring "objectives" for the learning_curve task since "metrics" is already specified.
`

**Comment by desilinguist** [comment] 2018-01-29 15:58
I remember now that we have run into this issue before but didn't solve it. The problem is that we always have `objectives` defined because we always have a default value so it's hard to tell when the user has specified objectives and when we are using the default. For example, the default list of objectives is `["f1_score_macro"]`. However, the user can also specify the same exact list in the config file. So, how do we tell one case apart from the other and show the warning in the one case but not the other?

**Comment by desilinguist** [comment] 2018-01-29 16:00
Perhaps a solution would be to just print out the objectives being used earlier in the log so that the user sees that even though she didn't specify one, they are there and being overridden?

**Comment by desilinguist** [comment] 2018-01-29 16:07
Ah, actually, looks like the solution we decided on for #381 (removing the defaults entirely in v2.0) should make this issue solvable too.

**Comment by aoifecahill** [comment] 2018-01-29 20:50
ah, yes I had forgotten that we had planned to remove the defaults (and hadn't remembered that that's what would trigger this confusing warning). Thanks for looking into it!

**Comment by desilinguist** [comment] 2018-04-29 22:28
Still working on it.

**Comment by desilinguist** [comment] 2018-07-28 23:38
Keep it open please.

**Comment by aoifecahill** [comment] 2018-10-26 23:58
keep it open please

**Comment by desilinguist** [comment] 2019-01-26 04:53
Keep it open please

**Comment by desilinguist** [comment] 2019-02-13 15:19
Addressed by #458.

**Closed by desilinguist** 2019-02-13 15:19 UTC
