### ISSUE TITLE
Use pathlib

### ISSUE THREAD

**Issue by mulhod** [EducationalTestingService/skll#637] opened 2020-11-09 14:10 UTC
This is actually a bit involved. It would be best to start by tackling 1-2 functions/methods at a time. Find a function/method that uses a file path string and make it be able to handle Path or str objects, for example.

**Comment by desilinguist** [comment] 2020-11-09 14:41
@mulhod I think this is a duplicate of #603 so may be you want to close that one?

**Closed** 2023-05-10 17:43 UTC
Labels: enhancement, help wanted
