### ISSUE TITLE
Unit tests for converting .lbsvm fail on Windows when run with Python 2.7

### ISSUE THREAD

**Issue by aloukina** [EducationalTestingService/skll#289] opened 2016-02-12 19:50 UTC
The following tests fail with `UnicodeEncodeError` error when ran from standard windows `cmd`:

`test_utilities.test_skll_convert` : when one of the file formats is .libsvm
`test_skll_convert_libsvm_map`

**Comment by desilinguist** [comment] 2017-12-27 16:57
Can you reproduce this, Matt?

**Comment by mulhod** [comment] 2017-12-27 16:58
Actually, no, I can't/I haven't tried. I just thought it shouldn't be closed probably since nothing has been done to address it. Should it be closed?

**Comment by desilinguist** [comment] 2017-12-27 17:04
I think we should close it because I can’t reproduce it. If someone else
can, they should reopen it.

**Comment by mulhod** [comment] 2017-12-27 18:07
I will close it, then. Maybe I can try to reproduce it later and will reopen if necessary.

**Closed by mulhod** 2017-12-27 18:07 UTC
